# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: attendee_service.proto for package 'attendees'

require 'grpc'
require_relative 'attendee_service_pb'

module Attendees
  module Attendees
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'attendees.Attendees'

      rpc :GetAttendee, ::Attendees::AttendeeRequest, ::Attendees::AttendeeResponse
      rpc :GetConferenceAttendees, ::Attendees::AttendeesRequest, stream(::Attendees::Attendee)
    end

    Stub = Service.rpc_stub_class
  end
end
